export const BUSINESS_GUIDES = {
  // --- 1. Naturaleza ---
  justificacion: { desc: 'Explica POR QUÉ existe tu negocio. ¿Qué problema real resuelves y por qué ahora es el momento correcto?', ejemplo: 'Ej: "En Hermosillo, el 68% de profesionistas no tienen un plan patrimonial. Jubilus nace para cerrar esa brecha con asesoría accesible."' },
  origen: { desc: 'Cuenta la historia de cómo surgió la idea. ¿Fue experiencia personal, un hueco en el mercado o una investigación?', ejemplo: 'Ej: "La idea nació cuando el fundador detectó que sus colegas perdían dinero por falta de educación financiera básica."' },
  nombre: { desc: 'Nombre comercial y razón detrás de la elección. Debe ser memorable y reflejar la identidad del negocio.', ejemplo: 'Ej: "Jubilus Consultores – del latín jubilum (alegría), evoca la tranquilidad de un futuro financiero seguro."' },
  descripcion: { desc: 'Resumen ejecutivo del negocio en 3-5 oraciones. Qué haces, para quién y cómo.', ejemplo: 'Ej: "Firma de consultoría patrimonial dirigida a profesionistas de 25-45 años en Sonora, ofreciendo planes personalizados de inversión y protección."' },
  mision: { desc: 'Propósito fundamental de la empresa. ¿Para qué existes HOY? Debe ser concreta y orientada a la acción.', ejemplo: 'Ej: "Democratizar la asesoría patrimonial en el noroeste de México mediante herramientas accesibles y transparentes."' },
  vision: { desc: 'Aspiración a futuro (3-5 años). ¿Qué quieres lograr? Debe ser ambiciosa pero alcanzable.', ejemplo: 'Ej: "Ser la firma de consultoría patrimonial #1 en Sonora para 2028, con más de 5,000 clientes activos."' },
  valores: { desc: 'Principios éticos que guían las decisiones del equipo. Lista 3-5 valores con una breve explicación de cada uno.', ejemplo: 'Ej: "Transparencia: Cero comisiones ocultas. Accesibilidad: Planes desde $500/mes. Innovación: Herramientas digitales de vanguardia."' },
  general: { desc: 'Objetivo macro del proyecto. Debe ser SMART: Específico, Medible, Alcanzable, Relevante, con Tiempo definido.', ejemplo: 'Ej: "Alcanzar 500 clientes activos y $2M MXN en activos bajo gestión dentro de los primeros 18 meses de operación."' },
  especificos: { desc: 'Desglose del objetivo general en 3-5 metas tácticas. Cada una debe tener un indicador claro.', ejemplo: 'Ej: "1) Lanzar la plataforma digital en Q1. 2) Captar 50 clientes/mes vía redes sociales. 3) Obtener certificación AMIB."' },
  metas: { desc: 'Números concretos con fecha. Ventas, clientes, ingresos, participación de mercado, etc.', ejemplo: 'Ej: "Mes 6: 150 clientes. Mes 12: $800K ingresos. Mes 18: Punto de equilibrio. Mes 24: Expansión a Baja California."' },
  fortalezas: { desc: 'Ventajas internas que te diferencian de la competencia. Recursos, talento, tecnología propia.', ejemplo: 'Ej: "Equipo con certificación AMIB, plataforma digital propia, alianzas con 3 aseguradoras líderes."' },
  oportunidades: { desc: 'Factores externos favorables que puedes aprovechar. Tendencias, vacíos de mercado, regulaciones nuevas.', ejemplo: 'Ej: "Crecimiento del 23% anual en inversiones digitales en México. Nueva ley de educación financiera obligatoria."' },
  debilidades: { desc: 'Limitaciones internas actuales. Sé honesto: falta de capital, equipo pequeño, marca nueva.', ejemplo: 'Ej: "Marca sin reconocimiento regional. Presupuesto de marketing limitado a $15K/mes. Solo 2 asesores certificados."' },
  amenazas: { desc: 'Riesgos externos que podrían afectarte. Competencia agresiva, cambios regulatorios, crisis económica.', ejemplo: 'Ej: "Entrada de fintechs internacionales (Betterment, GBM+). Volatilidad en tasas de interés de Banxico."' },
  politico: { desc: 'Leyes, regulaciones, estabilidad gubernamental y políticas fiscales que impactan tu operación.', ejemplo: 'Ej: "La reforma fiscal 2025 exige facturación 4.0, lo cual beneficia la formalización de servicios de consultoría."' },
  economico: { desc: 'Inflación, tipo de cambio, poder adquisitivo, tasas de interés y ciclo económico actual.', ejemplo: 'Ej: "Inflación del 4.2% con tasa Banxico al 10.5%. Clase media sonorense con ingreso promedio de $18K mensuales."' },
  social: { desc: 'Demografía, tendencias culturales, hábitos de consumo y nivel educativo de tu mercado.', ejemplo: 'Ej: "Generación millennial (30-40 años) en Hermosillo muestra interés creciente en finanzas personales según encuesta INEGI 2024."' },
  tecnologico: { desc: 'Infraestructura digital disponible, innovaciones del sector y nivel de adopción tecnológica.', ejemplo: 'Ej: "Penetración de smartphones del 89% en Sonora. APIs bancarias abiertas permiten integración en tiempo real."' },
  ecologico: { desc: 'Impacto ambiental de tu operación y tendencias de sustentabilidad relevantes.', ejemplo: 'Ej: "Operación 100% digital sin oficina física reduce huella de carbono. Cumplimos NOM-161 de residuos electrónicos."' },
  legal: { desc: 'Marco jurídico que regula tu industria. Permisos, certificaciones y obligaciones legales.', ejemplo: 'Ej: "Requiere registro ante CNBV y cumplimiento de la Ley del Mercado de Valores. NDA obligatorio con cada cliente."' },
  constitucion: { desc: 'Tipo de persona moral o física. Régimen fiscal elegido y justificación.', ejemplo: 'Ej: "S.A. de C.V. bajo régimen general de ley. Capital social de $50,000 MXN con 3 socios fundadores."' },
  socios: { desc: 'Lista de inversionistas, socios fundadores y su porcentaje de participación.', ejemplo: 'Ej: "Roberto Celis (40%), Ana García (30%), Luis Acosta (30%). Inversionista ángel: FundSonora ($200K MXN)."' },
  permisos: { desc: 'Licencias y trámites necesarios para operar legalmente. Incluye tiempos estimados.', ejemplo: 'Ej: "Licencia municipal de Hermosillo (3 semanas). RFC con actividad 5411 (inmediato). Registro IMSS patronal (5 días)."' },
  // --- 2. Mercado ---
  producto: { desc: 'Descripción técnica y funcional de tu producto o servicio. ¿Qué entregas exactamente?', ejemplo: 'Ej: "Plan patrimonial personalizado que incluye: diagnóstico financiero, portafolio de inversión y seguro de vida."' },
  valor: { desc: 'Tu promesa única al cliente. ¿Por qué te elegirían sobre la competencia?', ejemplo: 'Ej: "Asesoría sin conflicto de interés: cobramos honorarios fijos, no comisiones por producto vendido."' },
  demanda: { desc: 'Evidencia de que existe un mercado real dispuesto a pagar. Datos duros, encuestas, tendencias.', ejemplo: 'Ej: "Según AMAFORE, solo 22% de trabajadores en Sonora tiene un plan de retiro privado. Encuesta propia: 78% de 200 encuestados pagaría por asesoría."' },
  cliente: { desc: 'Perfil detallado de tu comprador ideal. Edad, ingreso, dolor principal, comportamiento.', ejemplo: 'Ej: "Profesionista de 28-42 años, ingreso $20-50K/mes, preocupado por su retiro, busca opciones digitales y transparentes."' },
  tam: { desc: 'Mercado Total Direccionable. Todo el mercado posible si no tuvieras limitaciones.', ejemplo: 'Ej: "3.2M de profesionistas en México que no tienen asesor financiero = $9.6B MXN anuales en fees potenciales."' },
  sam: { desc: 'Mercado Alcanzable. La porción del TAM que podrías servir con tu modelo actual.', ejemplo: 'Ej: "185,000 profesionistas en Sonora con ingreso >$20K/mes = $370M MXN anuales en servicios de consultoría."' },
  som: { desc: 'Mercado Obtenible. La rebanada realista que planeas capturar en 1-3 años.', ejemplo: 'Ej: "Capturar 0.5% del SAM = 925 clientes generando $5.5M MXN anuales en el tercer año."' },
  perfil: { desc: 'Características psicográficas: estilo de vida, valores, motivaciones y hábitos de compra.', ejemplo: 'Ej: "Valora la seguridad sobre el riesgo. Investiga en YouTube antes de comprar. Prefiere apps sobre llamadas telefónicas."' },
  competidores: { desc: 'Lista de competidores directos e indirectos con sus fortalezas y debilidades.', ejemplo: 'Ej: "Directos: GBM+ (digital, masivo), Actinver (premium). Indirectos: YouTube financiero, apps como Fintual."' },
  ventajas: { desc: 'Lo que te hace superior frente a cada competidor identificado.', ejemplo: 'Ej: "vs GBM+: Asesoría personalizada humana. vs Actinver: Accesibilidad (monto mínimo de $500 vs $100K)."' },
  comparativa: { desc: 'Tabla comparativa entre tu negocio y los líderes del sector en variables clave.', ejemplo: 'Ej: "Precio: Nosotros $500/mes vs Competidor A $2,000/mes. Personalización: Alta vs Media. Digital: 100% vs 40%."' },
  matriz: { desc: 'Mapa visual donde posicionas tu marca frente a competidores en dos ejes estratégicos.', ejemplo: 'Ej: "Eje X: Precio (bajo-alto). Eje Y: Personalización (masivo-premium). Nosotros: precio bajo + alta personalización."' },
  distribucion: { desc: 'Cómo llega tu producto al cliente. Canales físicos, digitales, directos o intermediarios.', ejemplo: 'Ej: "Canal 1: App móvil propia (60%). Canal 2: Referidos de despachos contables (25%). Canal 3: Eventos empresariales (15%)."' },
  promocion: { desc: 'Estrategia de comunicación para atraer clientes. Medios, presupuesto, frecuencia y métricas.', ejemplo: 'Ej: "Instagram Ads: $8K/mes, CTR esperado 2.5%. Webinars mensuales gratuitos. Programa de referidos: $500 por cliente nuevo."' },
  identidad: { desc: 'Elementos visuales de la marca: logo, paleta de colores, tipografía, tono de comunicación.', ejemplo: 'Ej: "Logo: Escudo dorado minimalista. Colores: Azul marino (#1e3a5f) + dorado (#d4a543). Tono: Profesional pero cercano."' },
  precios: { desc: 'Estrategia de fijación de precios. Método usado (costo+margen, competencia, valor percibido).', ejemplo: 'Ej: "Plan Básico: $500/mes. Plan Pro: $1,500/mes. Plan VIP: $3,500/mes. Basado en valor percibido con margen del 65%."' },
  estrategia: { desc: 'Tácticas de venta: embudo, ciclo de venta, guiones, CRM, seguimiento post-venta.', ejemplo: 'Ej: "Embudo: Contenido orgánico → Webinar gratuito → Consulta 1:1 → Cierre. Ciclo promedio: 14 días. CRM: HubSpot Free."' },
  proyeccion_volumen: { desc: 'Estimación de unidades vendidas por mes/trimestre/año. Base el cálculo en datos reales.', ejemplo: 'Ej: "Mes 1-3: 15 clientes/mes. Mes 4-6: 30/mes. Mes 7-12: 50/mes. Año 2: 80/mes. Total año 1: 350 clientes."' },
  heatmap_data: { desc: 'Datos de densidad de clientes potenciales por zona. Puede ser geográfico o por segmento digital.', ejemplo: 'Ej: "Zona Río: Densidad alta (35%). Centro: Media (20%). Sur Hermosillo: Baja (10%). Redes: LinkedIn 40%, IG 35%."' },
  // --- 3. Técnico ---
  macro: { desc: 'Análisis de la región, estado o ciudad elegida. Justifica con datos económicos y logísticos.', ejemplo: 'Ej: "Hermosillo, Sonora: PIB estatal de $430B MXN. Hub de servicios financieros del noroeste. Aeropuerto internacional."' },
  micro: { desc: 'Ubicación exacta dentro de la ciudad. Colonia, calle, accesibilidad, competencia cercana.', ejemplo: 'Ej: "Col. Villa de Seris, Blvd. Rosales #245. A 5 min del centro financiero. Renta: $12K/mes. Estacionamiento para 8 autos."' },
  local: { desc: 'Distribución física del espacio de trabajo. Metros cuadrados, zonas y mobiliario.', ejemplo: 'Ej: "Oficina de 80m²: Recepción (15m²), 2 oficinas privadas (12m² c/u), sala de juntas (20m²), coworking (21m²)."' },
  diagrama: { desc: 'Flujograma del proceso principal en formato Mermaid.js. Debe mostrar inicio, etapas y fin.', ejemplo: 'Ej: "graph TD → A[Prospecto] → B[Diagnóstico] → C[Propuesta] → D[Firma contrato] → E[Implementación] → F[Seguimiento]"' },
  proceso: { desc: 'Explicación paso a paso de cómo se entrega el servicio o se fabrica el producto.', ejemplo: 'Ej: "1. Cliente agenda cita (app). 2. Diagnóstico financiero (1hr). 3. Diseño de portafolio (48hrs). 4. Presentación y firma. 5. Monitoreo mensual."' },
  maquinaria: { desc: 'Listado de equipo especializado con marca, modelo, costo y vida útil estimada.', ejemplo: 'Ej: "2 MacBook Pro M3 ($45K c/u). 1 Servidor NAS Synology ($18K). Monitor 4K Dell ($12K). Total: $120K."' },
  equipo: { desc: 'Mobiliario de oficina, vehículos y equipo de cómputo general.', ejemplo: 'Ej: "4 escritorios ejecutivos ($8K c/u). 6 sillas ergonómicas ($5K c/u). Proyector Epson ($15K). Total: $77K."' },
  herramientas: { desc: 'Software, licencias, suscripciones y herramientas digitales necesarias.', ejemplo: 'Ej: "HubSpot CRM ($0). Suite Adobe ($600/mes). Zoom Pro ($250/mes). Dominio + hosting ($2K/año). Bloomberg Terminal ($24K/año)."' },
  materia_prima: { desc: 'Insumos principales para operar. En servicios: materiales de soporte, plataformas, data.', ejemplo: 'Ej: "Datos de mercado (Reuters, $5K/mes). Papelería corporativa ($2K/mes). Bases de datos CNBV (gratuito)."' },
  proveedores: { desc: 'Lista de proveedores clave con nombre, ubicación, condiciones de pago y alternativas.', ejemplo: 'Ej: "Proveedor 1: AWS (hosting, crédito de $1K). Proveedor 2: Imprenta GraficSon (30 días crédito). Alternativa: DigitalOcean."' },
  compras: { desc: 'Política de adquisiciones: frecuencia, volumen mínimo, control de calidad, inventario de seguridad.', ejemplo: 'Ej: "Compras de papelería: mensual. Software: anual con descuento. Criterio: mínimo 3 cotizaciones. Pago a 30 días."' },
  capacidad: { desc: 'Cuántos clientes/productos puedes atender con tu infraestructura actual.', ejemplo: 'Ej: "Capacidad actual: 200 clientes/mes con 2 asesores. Capacidad máxima: 500 clientes con 5 asesores y automatización."' },
  inventarios: { desc: 'Método de control de existencias (PEPS, UEPS, ABC) y software utilizado.', ejemplo: 'Ej: "Para servicios: Control de citas vía Calendly. Para productos: Método PEPS en Excel con alerta de stock mínimo."' },
  mano_obra: { desc: 'Personal necesario por área con perfil, cantidad, turno y tipo de contratación.', ejemplo: 'Ej: "2 asesores financieros (planta). 1 community manager (medio tiempo). 1 contador (outsourcing). 1 desarrollador (freelance)."' },
  impacto: { desc: 'Efectos de tu operación en el medio ambiente. Consumo energético, residuos, emisiones.', ejemplo: 'Ej: "Oficina consume 450 kWh/mes. Operación digital reduce 80% de papel vs firma tradicional. Huella: 2.3 ton CO₂/año."' },
  mitigacion: { desc: 'Acciones concretas para reducir tu impacto ambiental. Metas y plazos.', ejemplo: 'Ej: "Meta 2025: 100% firmas digitales. 2026: Energía solar en oficina (-60% consumo). Reciclaje de e-waste con certificado."' },
  normatividad: { desc: 'Leyes ambientales aplicables y tu nivel de cumplimiento actual.', ejemplo: 'Ej: "Cumplimos NOM-161-SEMARNAT (residuos electrónicos). Exentos de Licencia Ambiental por ser servicio de bajo impacto."' },
  // --- 4. Organización ---
  organigrama_visual: { desc: 'Código Mermaid.js que genera el organigrama del equipo jerárquicamente.', ejemplo: 'Ej: "graph TD → CEO → Dir. Financiero + Dir. Comercial → cada uno con sus subordinados"' },
  funciones: { desc: 'Tabla de responsabilidades de cada puesto clave. Qué hace, a quién reporta, KPIs.', ejemplo: 'Ej: "Director Comercial: Captación de clientes, gestión de embudo, reporta a CEO. KPI: 50 clientes nuevos/mes."' },
  reclutamiento: { desc: 'Proceso de atracción y selección de talento. Fuentes, filtros y tiempos.', ejemplo: 'Ej: "Publicación en LinkedIn + OCC. Filtro: CV → Entrevista técnica → Caso práctico → Contratación. Tiempo: 3 semanas."' },
  contratacion: { desc: 'Tipo de contrato, período de prueba, prestaciones y obligaciones patronales.', ejemplo: 'Ej: "Contrato indeterminado con 3 meses de prueba. Prestaciones de ley + seguro de gastos médicos mayores (6to mes)."' },
  sueldos: { desc: 'Tabla salarial por puesto incluyendo sueldo bruto, neto, prestaciones y costo total.', ejemplo: 'Ej: "Asesor Jr: $15K bruto + comisiones. Asesor Sr: $25K + bono. Dir. Comercial: $40K + 2% de ventas totales."' },
  capex: { desc: 'Inversión total en activos fijos: equipo, mobiliario, remodelación, tecnología.', ejemplo: 'Ej: "Equipo de cómputo: $120K. Mobiliario: $77K. Remodelación: $45K. Software: $30K. Total CAPEX: $272K."' },
  opex_inicial: { desc: 'Capital necesario para cubrir gastos operativos mientras el negocio no genera ingresos suficientes.', ejemplo: 'Ej: "6 meses de nómina: $300K. Renta: $72K. Marketing: $48K. Servicios: $18K. Total capital de trabajo: $438K."' },
  financiamiento: { desc: 'De dónde viene el dinero. Proporción de capital propio, préstamos e inversión externa.', ejemplo: 'Ej: "Capital propio: 60% ($430K). Crédito PyME Bancomext: 30% ($215K) a 5 años, tasa 12%. Inversionista ángel: 10% ($72K)."' },
  fijos: { desc: 'Gastos que no cambian sin importar el volumen de ventas: renta, nómina, servicios, seguros.', ejemplo: 'Ej: "Renta: $12K. Nómina: $95K. Luz/Internet: $3K. Software: $5K. Contador: $8K. Total fijos: $123K/mes."' },
  variables: { desc: 'Gastos que cambian según el número de clientes o unidades producidas.', ejemplo: 'Ej: "Comisión por cliente: $200. Impresión de reportes: $50/cliente. Café y amenidades: $30/cita. Costo variable: $280/cliente."' },
  unitario: { desc: 'Cálculo del costo total de atender a un solo cliente o producir una unidad.', ejemplo: 'Ej: "Costo fijo unitario: $123K ÷ 200 clientes = $615. Costo variable: $280. Costo total unitario: $895/cliente."' },
  resultados: { desc: 'Proyección de ingresos menos gastos por mes/año. Muestra cuándo serás rentable.', ejemplo: 'Ej: "Año 1: Ingresos $1.2M - Gastos $1.8M = Pérdida ($600K). Año 2: Ingresos $3.6M - Gastos $2.1M = Utilidad $1.5M."' },
  balance: { desc: 'Foto financiera: Activos = Pasivos + Capital. Proyectado a 3-5 años.', ejemplo: 'Ej: "Año 1: Activos $710K | Pasivos $430K | Capital $280K. Año 3: Activos $2.8M | Pasivos $180K | Capital $2.62M."' },
  flujo_caja: { desc: 'Entradas y salidas de efectivo reales por mes. Crucial para no quedarte sin liquidez.', ejemplo: 'Ej: "Mes 1: Entrada $30K, Salida $150K, Saldo -$120K. Mes 6: Entrada $180K, Salida $135K, Saldo +$45K."' },
  punto_equilibrio: { desc: 'Número de clientes o ventas necesarias para cubrir todos los costos. Fórmula: CF ÷ (PVU - CVU).', ejemplo: 'Ej: "$123K ÷ ($1,500 - $280) = 101 clientes/mes para cubrir costos. Meta: alcanzarlo en el mes 8."' },
  indicadores: { desc: 'VAN (Valor Actual Neto) y TIR (Tasa Interna de Retorno) del proyecto a 5 años.', ejemplo: 'Ej: "VAN a 5 años (tasa 12%): $1.8M MXN (positivo = viable). TIR: 34% (superior al costo de capital). Payback: 22 meses."' }
};

export const SOCIAL_GUIDES = {
  // Identificacion
  beneficiarios: { desc: '¿A quiénes ayuda exactamente este proyecto? (Población objetivo)', ejemplo: 'Ej: 500 jóvenes de 15 a 18 años en rezago educativo en la colonia X.' },
  aliados: { desc: 'Instituciones, ONGs o líderes comunitarios que apoyarán el proyecto.', ejemplo: 'Ej: Fundación Y, Secretaría de Educación, Junta de Vecinos.' },
  oponentes: { desc: 'Actores que podrían oponerse al proyecto o verse afectados negativamente.', ejemplo: 'Ej: Sindicato de maestros locales (riesgo de rechazo por nuevos métodos).' },
  matriz_interes: { desc: 'Clasificación de actores por su nivel de poder e interés en el proyecto.', ejemplo: 'Ej: Gobierno local (Alto Poder, Bajo Interés) -> Estrategia: Mantener informado.' },
  problema_central: { desc: 'El problema público o social que busca resolverse (en negativo).', ejemplo: 'Ej: Alto índice de deserción escolar en educación media superior en la zona sur.' },
  causas_directas: { desc: 'Por qué ocurre el problema central de manera inmediata.', ejemplo: 'Ej: 1. Falta de recursos económicos. 2. Desinterés por el currículo tradicional.' },
  causas_indirectas: { desc: 'Causas subyacentes o de raíz que generan las causas directas.', ejemplo: 'Ej: Desempleo de los padres, falta de escuelas técnicas cercanas.' },
  efectos: { desc: 'Consecuencias de que el problema no se resuelva.', ejemplo: 'Ej: Aumento de la delincuencia juvenil, empleos precarizados a futuro.' },
  objetivo_central: { desc: 'El problema central convertido en estado positivo alcanzado.', ejemplo: 'Ej: Reducida la deserción escolar en educación media superior en la zona sur.' },
  medios: { desc: 'Las soluciones (causas en positivo) para lograr el objetivo.', ejemplo: 'Ej: 1. Becas de transporte. 2. Talleres extracurriculares atractivos.' },
  fines: { desc: 'Los impactos a largo plazo (efectos en positivo).', ejemplo: 'Ej: Disminución de la delincuencia, mayor inserción laboral formal.' },
  estrategias_posibles: { desc: 'Opciones de solución derivadas del árbol de objetivos.', ejemplo: 'Ej: Estrategia A (Becas económicas) vs Estrategia B (Creación de talleres técnicos).' },
  criterios_seleccion: { desc: 'Criterios usados para elegir la mejor estrategia (costo, impacto, viabilidad).', ejemplo: 'Ej: Se eligió la Estrategia B por mayor sostenibilidad e impacto a largo plazo.' },
  alternativa_elegida: { desc: 'La estrategia final que conformará el proyecto.', ejemplo: 'Ej: Creación de 3 talleres técnicos extracurriculares con equipo donado.' },
  // Diseño MML
  fin: { desc: 'Impacto a largo plazo al que el proyecto contribuye.', ejemplo: 'Ej: Contribuir a la reducción de la pobreza y marginación urbana en 5 años.' },
  proposito: { desc: 'El objetivo específico que el proyecto logrará (el objetivo central).', ejemplo: 'Ej: Jóvenes de 15-18 años completan capacitación técnica y se insertan laboralmente.' },
  indicadores_fin: { desc: 'Cómo se medirá el impacto a largo plazo.', ejemplo: 'Ej: % de reducción de pobreza en la colonia en 5 años (Fuente: CONEVAL).' },
  indicadores_proposito: { desc: 'Cómo se medirá el éxito inmediato del proyecto.', ejemplo: 'Ej: Al menos 300 jóvenes graduados en 12 meses, 40% con empleo a los 6 meses.' },
  lista_componentes: { desc: 'Bienes, servicios o productos tangibles que entrega el proyecto.', ejemplo: 'Ej: 1. Centro de cómputo equipado. 2. Manuales de robótica impresos.' },
  indicadores_componentes: { desc: 'Métricas de los productos entregados.', ejemplo: 'Ej: 20 computadoras instaladas operando. 500 manuales distribuidos.' },
  supuestos: { desc: 'Riesgos externos que DEBEN cumplirse para el éxito (fuera de control).', ejemplo: 'Ej: El gobierno mantiene el subsidio de luz. Los jóvenes no migran por violencia.' },
  descripcion_actividades: { desc: 'Las tareas necesarias para entregar los componentes.', ejemplo: 'Ej: Para el Componente 1: a) Cotizar equipos b) Comprar c) Instalar d) Probar.' },
  cronograma_macro: { desc: 'Resumen de tiempos de las actividades principales.', ejemplo: 'Ej: Mes 1-2: Compras. Mes 3: Instalación. Mes 4-12: Talleres.' },
  medios_verificacion: { desc: 'Dónde se buscarán los datos para comprobar los indicadores.', ejemplo: 'Ej: Listas de asistencia, registros de calificaciones, recibos de compra.' },
  linea_base: { desc: 'El estado del indicador antes del proyecto.', ejemplo: 'Ej: Actualmente 0 jóvenes capacitados. Deserción actual: 25%.' },
  frecuencia_medicion: { desc: 'Cada cuánto se evaluarán los indicadores.', ejemplo: 'Ej: Asistencia: Semanal. Inserción laboral: Trimestral posterior al egreso.' },
  // Ejecucion
  comite_directivo: { desc: 'Quién toma las decisiones macro del proyecto.', ejemplo: 'Ej: Mesa conformada por el Director de la ONG, un donante y un líder vecinal.' },
  unidad_ejecutora: { desc: 'El equipo que opera el proyecto día a día.', ejemplo: 'Ej: 1 Coordinador, 3 profesores técnicos, 1 trabajador social.' },
  paquetes_trabajo: { desc: 'Agrupación de actividades en bloques manejables (EDT).', ejemplo: 'Ej: Paquete 1: Infraestructura. Paquete 2: Currícula. Paquete 3: Difusión.' },
  hitos_principales: { desc: 'Momentos clave de éxito en el cronograma.', ejemplo: 'Ej: Hito 1: Aula terminada (Mes 3). Hito 2: Inicio de clases (Mes 4).' },
  riesgos_identificados: { desc: 'Posibles eventos que amenacen el proyecto (Sociales, Políticos, etc.).', ejemplo: 'Ej: Robo de equipo de cómputo en la escuela comunitaria.' },
  plan_mitigacion: { desc: 'Qué se hará para prevenir o reaccionar a esos riesgos.', ejemplo: 'Ej: Instalar protecciones de herrería y crear comité de vigilancia vecinal.' },
  matriz_probabilidad: { desc: 'Clasificación de riesgos (Impacto x Probabilidad).', ejemplo: 'Ej: Robo (Probabilidad Alta, Impacto Alto) -> Prioridad Crítica.' },
  audiencias: { desc: 'Grupos clave que deben recibir información del avance.', ejemplo: 'Ej: Donantes (BID), Padres de familia, Autoridades educativas.' },
  canales: { desc: 'Medios a través de los cuales se enviará la información.', ejemplo: 'Ej: Reporte trimestral PDF para BID. Grupo de WhatsApp para padres.' },
  mensajes_clave: { desc: 'Lo que se quiere comunicar a cada audiencia.', ejemplo: 'Ej: A los padres: "Su hijo está adquiriendo habilidades para el futuro".' },
  // Presupuesto
  costos_directos: { desc: 'Dinero gastado directamente en la intervención social.', ejemplo: 'Ej: Pago a instructores ($150k), Computadoras ($200k), Materiales ($50k).' },
  costos_indirectos: { desc: 'Gastos de administración y logística (overhead).', ejemplo: 'Ej: Sueldo del director ($50k), Papelería de oficina ($10k), Contador ($15k).' },
  fuentes_financiamiento: { desc: 'Quién aporta el dinero (donantes, contrapartida local, etc.).', ejemplo: 'Ej: BID aporta 70% ($350k). Contrapartida local en especie (local prestado) 30%.' },
  beneficios_sociales: { desc: 'Valorización monetaria del impacto (Ej. incremento de sueldo futuro).', ejemplo: 'Ej: Los graduados ganarán $30,000 extra al año. En 500 jóvenes = $15M anuales.' },
  tir_social: { desc: 'Tasa Interna de Retorno pero midiendo beneficios a la sociedad, no ganancias.', ejemplo: 'Ej: TIR Social estimada: 25% (muy superior a la tasa de descuento social del 10%).' },
  vpn_social: { desc: 'Valor Presente Neto de los beneficios sociales menos el costo del proyecto.', ejemplo: 'Ej: Valor Presente Neto Social: +$4.5 Millones a 5 años.' },
  sostenibilidad_financiera: { desc: 'Cómo se pagará la operación cuando termine el donativo.', ejemplo: 'Ej: Se cobrará una cuota de recuperación simbólica y se venderán servicios de consultoría técnica de los estudiantes.' },
  sostenibilidad_institucional: { desc: 'Quién se hará cargo de administrar el proyecto a futuro.', ejemplo: 'Ej: La asociación de padres asumirá el control directivo en el Año 3.' },
  apropiacion_comunitaria: { desc: 'Cómo asegurar que la comunidad defienda y mantenga el proyecto.', ejemplo: 'Ej: Involucrar a los jóvenes en pintar y decorar el aula para generar sentido de pertenencia.' }
};
