/**
 * SwarmIntelligenceHub.jsx - Panel de Control y Biblioteca de Agentes Evolutivos
 * 
 * Permite explorar el catálogo permanente de agentes del AgentStore, visualizar métricas
 * de ahorro de tokens y efectividad, exportar el bundle mensual para Fondo Thoth AC
 * y sincronizar telemetría hacia la nube.
 */

import React, { useState, useEffect } from 'react';
import { Download, Cloud, Sparkles, CheckCircle2, ShieldCheck, Zap, Bot, RefreshCw, X, Filter, Activity } from 'lucide-react';

export function SwarmIntelligenceHub({ isOpen, onClose }) {
  const [agents, setAgents] = useState([]);
  const [metrics, setMetrics] = useState({ totalTokensSaved: 0, totalUses: 0, count: 0 });
  const [isLoading, setIsLoading] = useState(true);
  const [syncStatus, setSyncStatus] = useState(null);
  const [selectedTag, setSelectedTag] = useState('all');

  const fetchAgents = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('http://localhost:3001/api/swarm/agents');
      if (res.ok) {
        const data = await res.json();
        setAgents(data.agents || []);
        setMetrics({
          totalTokensSaved: data.totalTokensSaved || 0,
          totalUses: data.totalUses || 0,
          count: data.count || 0
        });
      }
    } catch (err) {
      console.error('Error al obtener catálogo de agentes:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      fetchAgents();
    }
  }, [isOpen]);

  const handleSyncCloud = async () => {
    setSyncStatus({ loading: true, message: 'Sincronizando con Fondo Thoth Cloud...' });
    try {
      const res = await fetch('http://localhost:3001/api/v1/swarm/sync-skills', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' }
      });
      const data = await res.json();
      if (data.success) {
        setSyncStatus({ success: true, message: '¡Telemetría y nuevos skills sincronizados exitosamente!' });
        setTimeout(() => setSyncStatus(null), 4000);
      } else {
        setSyncStatus({ error: true, message: 'Error en respuesta de sincronización.' });
      }
    } catch (err) {
      setSyncStatus({ error: true, message: `Error de conexión: ${err.message}` });
    }
  };

  const handleExportBundle = () => {
    window.open('http://localhost:3001/api/swarm/export-bundle', '_blank');
  };

  if (!isOpen) return null;

  const filteredAgents = agents.filter((agent) => {
    if (selectedTag === 'all') return true;
    if (selectedTag === 'auto' && (agent.isAutoGenerated || agent.isSpecialized)) return true;
    return (agent.domain || []).some(d => d.toLowerCase().includes(selectedTag));
  });

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 animate-fade-in">
      <div className="bg-slate-900 border border-slate-750 rounded-2xl w-full max-w-5xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        
        {/* Header con Métricas Globales */}
        <div className="p-6 border-b border-slate-800 bg-slate-950/80 flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-indigo-600/20 border border-indigo-500/30 rounded-xl text-indigo-400">
              <Bot size={28} />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-bold text-white tracking-tight">Swarm Intelligence Hub</h2>
                <span className="px-2.5 py-0.5 text-xs font-semibold rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                  v3.0 Kimi-Style
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Catálogo permanente de agentes especialistas, auto-generación y telemetría de Fondo Thoth AC
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleSyncCloud}
              disabled={syncStatus?.loading}
              className="flex items-center gap-2 px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-medium transition shadow-sm disabled:opacity-50"
            >
              <Cloud size={16} />
              {syncStatus?.loading ? 'Sincronizando...' : 'Sincronizar Cloud'}
            </button>
            <button
              onClick={handleExportBundle}
              className="flex items-center gap-2 px-3.5 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-medium transition shadow-sm"
            >
              <Download size={16} />
              Exportar Bundle Mensual
            </button>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-lg transition"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Tarjetas de Métricas de Ahorro */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 p-6 bg-slate-900/60 border-b border-slate-800/80">
          <div className="p-4 rounded-xl bg-slate-800/50 border border-slate-700/60 flex items-center gap-4">
            <div className="p-3 bg-amber-500/10 text-amber-400 rounded-lg">
              <Zap size={22} />
            </div>
            <div>
              <div className="text-2xl font-black text-white">{metrics.totalTokensSaved.toLocaleString()}</div>
              <div className="text-xs text-slate-400 font-medium">Tokens Ahorrados por Reutilización</div>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-slate-800/50 border border-slate-700/60 flex items-center gap-4">
            <div className="p-3 bg-emerald-500/10 text-emerald-400 rounded-lg">
              <ShieldCheck size={22} />
            </div>
            <div>
              <div className="text-2xl font-black text-white">{metrics.count} Agentes</div>
              <div className="text-xs text-slate-400 font-medium">Capacidades en Store Permanente</div>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-slate-800/50 border border-slate-700/60 flex items-center gap-4">
            <div className="p-3 bg-cyan-500/10 text-cyan-400 rounded-lg">
              <Activity size={22} />
            </div>
            <div>
              <div className="text-2xl font-black text-white">{metrics.totalUses} Ejecuciones</div>
              <div className="text-xs text-slate-400 font-medium">Llamadas Concurrentes Exitosas</div>
            </div>
          </div>
        </div>

        {/* Notificaciones de sincronización */}
        {syncStatus && (
          <div className={`px-6 py-2 text-xs font-medium flex items-center gap-2 ${
            syncStatus.success ? 'bg-emerald-950/80 text-emerald-300 border-b border-emerald-800' :
            syncStatus.error ? 'bg-rose-950/80 text-rose-300 border-b border-rose-800' :
            'bg-indigo-950/80 text-indigo-300 border-b border-indigo-800'
          }`}>
            <Sparkles size={14} />
            {syncStatus.message}
          </div>
        )}

        {/* Filtros de Dominio */}
        <div className="px-6 py-3 border-b border-slate-800 flex items-center gap-2 overflow-x-auto">
          <Filter size={14} className="text-slate-400 mr-1 shrink-0" />
          {[
            { id: 'all', label: 'Todos' },
            { id: 'auto', label: '✨ Auto-Generados & Especializados' },
            { id: 'cuantico', label: '⚛️ Cuántico' },
            { id: 'mercado', label: '🕵️ Mercado' },
            { id: 'finanzas', label: '📊 Finanzas' },
            { id: 'estrategia', label: '🧭 Estrategia' },
            { id: 'social', label: '🤝 Social BID' },
            { id: 'tecnologia', label: '🔬 I+D' }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setSelectedTag(tab.id)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition whitespace-nowrap ${
                selectedTag === tab.id
                  ? 'bg-indigo-600 text-white shadow-sm'
                  : 'bg-slate-800/80 text-slate-300 hover:bg-slate-750'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Grid de Agentes */}
        <div className="p-6 overflow-y-auto flex-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {isLoading ? (
            <div className="col-span-full py-16 flex flex-col items-center justify-center text-slate-400 gap-3">
              <RefreshCw className="animate-spin text-indigo-400" size={32} />
              <p className="text-sm">Cargando biblioteca permanente de agentes...</p>
            </div>
          ) : filteredAgents.length === 0 ? (
            <div className="col-span-full py-16 text-center text-slate-400">
              No se encontraron agentes con el filtro seleccionado.
            </div>
          ) : (
            filteredAgents.map(agent => (
              <div
                key={agent.id}
                className="bg-slate-800/60 border border-slate-700/60 rounded-xl p-4 flex flex-col justify-between hover:border-indigo-500/40 transition group"
              >
                <div>
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <div className="flex items-center gap-2">
                      <span className="text-2xl">{agent.avatar || '🤖'}</span>
                      <div>
                        <h4 className="text-sm font-bold text-white group-hover:text-indigo-300 transition">
                          {agent.name}
                        </h4>
                        <span className="text-[10px] text-slate-400 block font-mono">ID: {agent.id}</span>
                      </div>
                    </div>
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-indigo-500/10 text-indigo-300 border border-indigo-500/20">
                      ★ {agent.evaluationScore || agent.metrics?.averageRating || 9.5}
                    </span>
                  </div>

                  <p className="text-xs text-slate-300 mb-3 line-clamp-2">
                    {agent.role}
                  </p>

                  {/* Badges de Dominio */}
                  <div className="flex flex-wrap gap-1 mb-3">
                    {(agent.domain || []).slice(0, 3).map((d, i) => (
                      <span key={i} className="px-2 py-0.5 rounded bg-slate-900/80 text-slate-400 text-[10px]">
                        #{d}
                      </span>
                    ))}
                    {(agent.domain || []).length > 3 && (
                      <span className="px-1.5 py-0.5 rounded bg-slate-900/80 text-slate-500 text-[10px]">
                        +{agent.domain.length - 3}
                      </span>
                    )}
                  </div>
                </div>

                <div className="pt-3 border-t border-slate-700/50 flex items-center justify-between text-[11px] text-slate-400">
                  <span className="flex items-center gap-1">
                    <Zap size={12} className="text-amber-400" />
                    {(agent.metrics?.tokensSaved || 0).toLocaleString()} tks
                  </span>
                  <span className="flex items-center gap-1">
                    <CheckCircle2 size={12} className="text-emerald-400" />
                    {agent.metrics?.usageCount || 0} usos
                  </span>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-950 flex items-center justify-between text-xs text-slate-400">
          <span>Metodología Fondo Thoth AC — Swarm Evolution Engine</span>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-lg transition"
          >
            Cerrar
          </button>
        </div>

      </div>
    </div>
  );
}
