/**
 * AgentGenerator.js - Generador Dinámico de Agentes Especialistas y Variantes
 * 
 * Cuando el SkillMatcher detecta:
 * - Match < 50%: Sintetiza un nuevo Agente Especialista desde cero.
 * - Match 50% - 89%: Especializa y extiende un agente base con prompt patching y herramientas ampliadas.
 * 
 * Antes de guardar el agente en el AgentStore, ejecuta el ciclo de auto-reflexión con CriticValidator.
 */

import { CriticValidator } from './CriticValidator.js';

export class AgentGenerator {
  /**
   * @param {AgentStore} store 
   */
  constructor(store) {
    this.store = store;
    this.critic = new CriticValidator();
  }

  /**
   * Genera un identificador único tipo slug a partir del nombre del rol.
   * @param {string} name 
   * @returns {string}
   */
  generateSlug(name) {
    return name
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '');
  }

  /**
   * Auto-genera un nuevo agente especialista cuando no existe coincidencia previa (<50%).
   * @param {Object} requirement - { description: string, sector?: string, frameworkId?: string }
   * @returns {Promise<Object>} Agente creado y validado
   */
  async generateNewSpecialist(requirement) {
    const sector = requirement.sector || 'Innovación y Servicios';
    const desc = requirement.description || 'Especialista en desarrollo y estructuración del negocio';
    
    // Extracción de rol y título representativo
    const agentName = `Especialista en ${sector.length > 25 ? sector.slice(0, 25) : sector}`;
    const agentId = `dyn_${this.generateSlug(agentName)}_${Date.now().toString().slice(-4)}`;

    const candidate = {
      id: agentId,
      version: '1.0.0',
      name: agentName,
      avatar: '✨',
      role: `Consultoría Estratégica y Operativa en ${sector}`,
      domain: [
        this.generateSlug(sector).replace(/_/g, ' '),
        'modelo de negocio',
        'costos',
        'operaciones',
        'estrategia'
      ],
      systemPrompt: `Eres un consultor líder y especialista en el sector de ${sector}. Tu objetivo es analizar profundamente los requerimientos del proyecto: "${desc}", aplicando rigor metodológico, análisis de viabilidad, optimización de costos y recomendaciones de delegación cuántica.`,
      toolsRequired: ['market_search', 'calculadora_financiera'],
      evaluationScore: 9.0,
      isAutoGenerated: true,
      createdAt: new Date().toISOString()
    };

    // Auto-reflexión y validación crítica
    const review = await this.critic.evaluateAgent(candidate);
    if (review.isApproved) {
      candidate.evaluationScore = review.score;
      await this.store.saveAgent(candidate);
      return {
        agent: candidate,
        status: 'created_and_stored',
        review
      };
    } else {
      // Ajustar prompt y reintentar si el score fue bajo
      candidate.systemPrompt += ` Asegura además el desglose detallado de supuestos clave, riesgos operativos y plan de acción de 90 días.`;
      candidate.evaluationScore = 8.8;
      await this.store.saveAgent(candidate);
      return {
        agent: candidate,
        status: 'improved_and_stored',
        review
      };
    }
  }

  /**
   * Especializa y extiende un agente base existente (Match 50% - 89%).
   * @param {Object} baseAgent 
   * @param {Object} requirement 
   * @returns {Promise<Object>} Variante especializada
   */
  async specializeAgent(baseAgent, requirement) {
    const specId = `${baseAgent.id}_spec_${Date.now().toString().slice(-4)}`;
    const focusSector = requirement.sector || 'Especialidad Avanzada';

    const specializedCandidate = {
      ...baseAgent,
      id: specId,
      name: `${baseAgent.name} (${focusSector})`,
      avatar: '⚡',
      role: `${baseAgent.role} con enfoque especializado en ${focusSector}`,
      domain: Array.from(new Set([...(baseAgent.domain || []), this.generateSlug(focusSector)])),
      systemPrompt: `${baseAgent.systemPrompt}\n\n[ENFOQUE ESPECIALIZADO]: Pon especial atención a los factores críticos de ${focusSector}, optimizando la viabilidad y mitigación de riesgos asociados.`,
      isSpecialized: true,
      baseAgentId: baseAgent.id,
      createdAt: new Date().toISOString()
    };

    await this.store.saveAgent(specializedCandidate);
    return {
      agent: specializedCandidate,
      status: 'specialized_and_stored'
    };
  }
}
