export const SCIAN_PRESETS = [
  { label: '0 · Todos los sectores', value: '0' },
  // 11 - Agricultura, cría y explotación de animales, silvicultura, pesca y caza
  { label: '11 · Agricultura, cría y explotación de animales, silvicultura, pesca y caza', value: '11' },
  { label: '111 · Agricultura', value: '111' },
  { label: '112 · Cría y explotación de animales', value: '112' },
  { label: '113 · Aprovechamiento forestal', value: '113' },
  { label: '114 · Pesca, caza y captura', value: '114' },
  { label: '115 · Servicios relacionados con las actividades agropecuarias y forestales', value: '115' },
  
  // 21 - Minería
  { label: '21 · Minería', value: '21' },
  { label: '211 · Extracción de petróleo y gas', value: '211' },
  { label: '212 · Minería de minerales metálicos y no metálicos, excepto petróleo y gas', value: '212' },
  { label: '213 · Servicios relacionados con la minería', value: '213' },
  
  // 22 - Suministros
  { label: '22 · Suministros (Electricidad, agua y gas)', value: '22' },
  { label: '221 · Generación, transmisión, distribución y comercialización de energía eléctrica, suministro de agua y de gas por ductos', value: '221' },
  { label: '222 · Suministro de agua y suministro de gas por ductos al consumidor final', value: '222' },
  
  // 23 - Construcción
  { label: '23 · Construcción', value: '23' },
  { label: '236 · Edificación', value: '236' },
  { label: '237 · Construcción de obras de ingeniería civil', value: '237' },
  { label: '238 · Trabajos especializados para la construcción', value: '238' },
  
  // 31-33 - Industrias manufactureras
  { label: '31-33 · Industrias manufactureras', value: '31-33' },
  { label: '311 · Industria alimentaria', value: '311' },
  { label: '3111 · Elaboración de alimentos para animales', value: '3111' },
  { label: '3112 · Molienda de granos y semillas y obtención de aceites y grasas alimenticias', value: '3112' },
  { label: '3113 · Elaboración de azúcares, chocolates, dulces y similares', value: '3113' },
  { label: '3114 · Conservación de frutas, verduras, guisados y otros alimentos preparados', value: '3114' },
  { label: '3115 · Elaboración de productos lácteos', value: '3115' },
  { label: '3116 · Matanza, empacado y procesamiento de carne de ganado, aves y otros animales comestibles', value: '3116' },
  { label: '3118 · Panadería y fabricación de tortillas', value: '3118' },
  { label: '312 · Industria de las bebidas y del tabaco', value: '312' },
  { label: '313 · Fabricación de insumos textiles y acabado de textiles', value: '313' },
  { label: '314 · Fabricación de productos textiles, excepto prendas de vestir', value: '314' },
  { label: '315 · Fabricación de prendas de vestir', value: '315' },
  { label: '316 · Curtido y acabado de cuero y piel, y fabricación de productos de cuero, piel y materiales sustitutos', value: '316' },
  { label: '321 · Industria de la madera', value: '321' },
  { label: '322 · Industria del papel', value: '322' },
  { label: '323 · Impresión e industrias conexas', value: '323' },
  { label: '324 · Fabricación de productos derivados del petróleo y del carbón', value: '324' },
  { label: '325 · Industria química', value: '325' },
  { label: '326 · Industria del plástico y del hule', value: '326' },
  { label: '327 · Fabricación de productos a base de minerales no metálicos', value: '327' },
  { label: '331 · Industrias metálicas básicas', value: '331' },
  { label: '332 · Fabricación de productos metálicos', value: '332' },
  { label: '333 · Fabricación de maquinaria y equipo', value: '333' },
  { label: '334 · Fabricación de equipo de computación, comunicación, medición y de otros equipos, componentes y accesorios electrónicos', value: '334' },
  { label: '335 · Fabricación de accesorios, aparatos eléctricos y equipo de generación de energía eléctrica', value: '335' },
  { label: '336 · Fabricación de equipo de transporte', value: '336' },
  { label: '337 · Fabricación de muebles, colchones y persianas', value: '337' },
  { label: '339 · Otras industrias manufactureras', value: '339' },
  
  // 43 - Comercio al por mayor
  { label: '43 · Comercio al por mayor', value: '43' },
  { label: '431 · Comercio al por mayor de abarrotes, alimentos, bebidas, hielo y tabaco', value: '431' },
  { label: '432 · Comercio al por mayor de productos textiles y calzado', value: '432' },
  { label: '433 · Comercio al por mayor de productos farmacéuticos, de perfumería, artículos para el esparcimiento, electrodomésticos menores y aparatos de línea blanca', value: '433' },
  { label: '434 · Comercio al por mayor de materias primas agropecuarias y forestales, para la industria, y materiales de desecho', value: '434' },
  { label: '435 · Comercio al por mayor de maquinaria, equipo y mobiliario para actividades agropecuarias, industriales, de servicios y comerciales, y de otra maquinaria y equipo de uso general', value: '435' },
  { label: '436 · Comercio al por mayor de camiones de carga, camiones de pasajeros, automóviles y motocicletas, partes y refacciones nuevas, y llantas', value: '436' },
  
  // 46 - Comercio al por menor
  { label: '46 · Comercio al por menor', value: '46' },
  { label: '461 · Comercio al por menor de abarrotes, alimentos, bebidas, hielo y tabaco', value: '461' },
  { label: '461110 · Comercio al por menor en tiendas de abarrotes, ultramarinos y misceláneas', value: '461110' },
  { label: '461121 · Comercio al por menor de carnes rojas', value: '461121' },
  { label: '461122 · Comercio al por menor de carne de aves', value: '461122' },
  { label: '461130 · Comercio al por menor de pescados y mariscos', value: '461130' },
  { label: '461140 · Comercio al por menor de leche, otros productos lácteos y embutidos', value: '461140' },
  { label: '461150 · Comercio al por menor de dulces y materias primas para repostería', value: '461150' },
  { label: '461160 · Comercio al por menor de frutas y verduras frescas', value: '461160' },
  { label: '461170 · Comercio al por menor de huevo', value: '461170' },
  { label: '461190 · Comercio al por menor de otros alimentos', value: '461190' },
  { label: '4612 · Comercio al por menor de bebidas, hielo y tabaco', value: '4612' },
  { label: '462 · Comercio al por menor en tiendas de autoservicio y departamentales', value: '462' },
  { label: '462111 · Comercio al por menor en supermercados', value: '462111' },
  { label: '462112 · Comercio al por menor en minisupers', value: '462112' },
  { label: '462210 · Comercio al por menor en tiendas departamentales', value: '462210' },
  { label: '463 · Comercio al por menor de artículos para la cuidado de la salud', value: '463' },
  { label: '463110 · Comercio al por menor de productos farmacéuticos y de medicina alternativa', value: '463110' },
  { label: '463211 · Comercio al por menor de artículos y aparatos ortopédicos', value: '463211' },
  { label: '463212 · Comercio al por menor de lentes y artículos oftalmológicos (Ópticas)', value: '463212' },
  { label: '464 · Comercio al por menor de artículos de papelería, para el esparcimiento y otros artículos de uso personal', value: '464' },
  { label: '464111 · Comercio al por menor de libros', value: '464111' },
  { label: '464112 · Comercio al por menor de periódicos y revistas', value: '464112' },
  { label: '464121 · Comercio al por menor de papelería', value: '464121' },
  { label: '464122 · Comercio al por menor de artículos de dibujo', value: '464122' },
  { label: '465 · Comercio al por menor de ropa, bisutería y accesorios de vestir', value: '465' },
  { label: '465111 · Comercio al por menor de ropa de vestir', value: '465111' },
  { label: '465211 · Comercio al por menor de calzado (Zapaterías)', value: '465211' },
  { label: '466 · Comercio al por menor de artículos para el hogar, excepto electrodomésticos', value: '466' },
  { label: '466111 · Comercio al por menor de muebles para el hogar', value: '466111' },
  { label: '467 · Comercio al por menor de artículos de ferretería, tlapalería y vidrios', value: '467' },
  { label: '467111 · Comercio al por menor en ferreterías y tlapalerías', value: '467111' },
  { label: '467112 · Comercio al por menor de pinturas', value: '467112' },
  { label: '467113 · Comercio al por menor de vidrios y espejos', value: '467113' },
  { label: '467115 · Comercio al por menor de materiales para la construcción', value: '467115' },
  { label: '468 · Comercio al por menor de vehículos de motor, refacciones, combustibles y lubricantes', value: '468' },
  { label: '468111 · Comercio al por menor de automóviles nuevos y usados', value: '468111' },
  { label: '468211 · Comercio al por menor de llantas y cámaras', value: '468211' },
  { label: '468212 · Comercio al por menor de refacciones y accesorios nuevos para vehículos', value: '468212' },
  { label: '468411 · Comercio al por menor de gasolina y diesel (Gasolineras)', value: '468411' },
  { label: '468420 · Comercio al por menor de gas licuado de petróleo', value: '468420' },
  
  // 48-49 - Transportes, correos y almacenamiento
  { label: '48-49 · Transportes, correos y almacenamiento', value: '48-49' },
  { label: '481 · Transporte aéreo', value: '481' },
  { label: '482 · Transporte por ferrocarril', value: '482' },
  { label: '483 · Transporte por agua', value: '483' },
  { label: '484 · Autotransporte de carga', value: '484' },
  { label: '485 · Transporte colectivo de pasajeros', value: '485' },
  { label: '485111 · Transporte colectivo urbano en autobús', value: '485111' },
  { label: '485210 · Autobuses de pasajeros foráneos', value: '485210' },
  { label: '485311 · Servicio de taxis de sitio', value: '485311' },
  { label: '488 · Servicios relacionados con el transporte', value: '488' },
  { label: '491 · Servicio postal', value: '491' },
  { label: '492 · Servicios de mensajería y paquetería', value: '492' },
  { label: '493 · Almacenamiento', value: '493' },
  
  // 51 - Información en medios masivos
  { label: '51 · Información en medios masivos', value: '51' },
  { label: '511 · Edición de software y publicaciones, excepto en internet', value: '511' },
  { label: '512 · Industria fílmica y del video, e industria del sonido', value: '512' },
  { label: '515 · Radio y televisión, excepto por internet', value: '515' },
  { label: '517 · Telecomunicaciones', value: '517' },
  { label: '518 · Procesamiento de datos, hospedaje de datos, y servicios relacionados', value: '518' },
  { label: '519 · Otros servicios de información', value: '519' },
  
  // 52 - Servicios financieros y de seguros
  { label: '52 · Servicios financieros y de seguros', value: '52' },
  { label: '522 · S. financieros no bursátiles (Bancos, cajas, empeño)', value: '522' },
  { label: '522110 · Banca múltiple (Bancos comerciales)', value: '522110' },
  { label: '522210 · Cajas de ahorro popular', value: '522210' },
  { label: '522430 · Casas de empeño', value: '522430' },
  { label: '523 · Actividades bursátiles, cambiarias y de inversión financiera', value: '523' },
  { label: '523310 · Casas de cambio', value: '523310' },
  { label: '524 · Compañías de seguros, fianzas, y administración de fondos', value: '524' },
  { label: '524110 · Compañías de seguros de vida y salud', value: '524110' },
  
  // 53 - Servicios inmobiliarios y de alquiler de bienes muebles e intangibles
  { label: '53 · Servicios inmobiliarios y de alquiler', value: '53' },
  { label: '531 · Servicios inmobiliarios', value: '531' },
  { label: '531111 · Alquiler de viviendas y departamentos', value: '531111' },
  { label: '531210 · Inmobiliarias y corredores de raíces', value: '531210' },
  { label: '532 · Servicios de alquiler de bienes muebles', value: '532' },
  { label: '532111 · Alquiler de automóviles sin chofer', value: '532111' },
  
  // 54 - Servicios profesionales, científicos y técnicos
  { label: '54 · Servicios profesionales, científicos y técnicos', value: '54' },
  { label: '541 · Servicios profesionales, científicos y técnicos', value: '541' },
  { label: '541110 · Bufetes jurídicos (Servicios legales)', value: '541110' },
  { label: '541211 · Despachos de contabilidad y auditoría', value: '541211' },
  { label: '541310 · Servicios de arquitectura', value: '541310' },
  { label: '541330 · Servicios de ingeniería', value: '541330' },
  { label: '541430 · Diseño gráfico y publicidad', value: '541430' },
  { label: '541510 · Consultoría en computación y desarrollo de software', value: '541510' },
  { label: '541810 · Agencias de publicidad', value: '541810' },
  { label: '541920 · Clínicas y hospitales veterinarios', value: '541920' },
  
  // 55 - Corporativos
  { label: '55 · Corporativos', value: '55' },
  { label: '551 · Corporativos', value: '551' },
  
  // 56 - Servicios de apoyo a los negocios y manejo de residuos y servicios de remediación
  { label: '56 · Servicios de apoyo a los negocios y manejo de residuos', value: '56' },
  { label: '561 · Servicios de apoyo a los negocios', value: '561' },
  { label: '561320 · Agencias de empleo temporal y reclutamiento', value: '561320' },
  { label: '561612 · Servicios de seguridad privada', value: '561612' },
  { label: '561720 · Servicios de limpieza de inmuebles', value: '561720' },
  
  // 61 - Servicios educativos
  { label: '61 · Servicios educativos', value: '61' },
  { label: '611111 · Escuelas de educación preescolar del sector privado', value: '611111' },
  { label: '611121 · Escuelas de educación primaria del sector privado', value: '611121' },
  { label: '611131 · Escuelas de educación secundaria del sector privado', value: '611131' },
  { label: '611161 · Escuelas de educación media superior del sector privado (Prepas)', value: '611161' },
  { label: '611312 · Escuelas de educación superior del sector privado (Universidades)', value: '611312' },
  { label: '611610 · Escuelas de arte del sector privado', value: '611610' },
  { label: '611620 · Escuelas de deporte y acondicionamiento físico privado', value: '611620' },
  { label: '611630 · Escuelas de idiomas del sector privado', value: '611630' },
  
  // 62 - Servicios de salud y de asistencia social
  { label: '62 · Servicios de salud y de asistencia social', value: '62' },
  { label: '621 · Servicios médicos de consulta externa y relacionados', value: '621' },
  { label: '621111 · Consultorios médicos del sector privado (Generalistas)', value: '621111' },
  { label: '621112 · Consultorios médicos de especialistas privado', value: '621112' },
  { label: '621210 · Consultorios dentales del sector privado', value: '621210' },
  { label: '621340 · Consultorios de quiropráctica y terapia física privado', value: '621340' },
  { label: '621391 · Consultorios de psicología del sector privado', value: '621391' },
  { label: '621511 · Laboratorios médicos y de diagnóstico clínicos privado', value: '621511' },
  { label: '622 · Hospitales', value: '622' },
  { label: '622110 · Hospitales generales del sector privado', value: '622110' },
  { label: '623 · Residencias de asistencia social y cuidado', value: '623' },
  { label: '624 · Otros servicios de asistencia social', value: '624' },
  { label: '624410 · Guarderías y estancias infantiles del sector privado', value: '624410' },
  
  // 71 - Servicios artísticos, culturales y deportivos, y otros servicios relacionados
  { label: '71 · Servicios artísticos, culturales y deportivos', value: '71' },
  { label: '711211 · Promotores de espectáculos artísticos y deportivos', value: '711211' },
  { label: '713120 · Parques de diversión y centros de entretenimiento', value: '713120' },
  { label: '713940 · Gimnasios y centros de acondicionamiento físico privado', value: '713940' },
  
  // 72 - Servicios de alojamiento temporal y de preparación de alimentos y bebidas
  { label: '72 · Servicios de alojamiento y alimentos', value: '72' },
  { label: '721 · Servicios de alojamiento temporal', value: '721' },
  { label: '721110 · Hoteles y moteles', value: '721110' },
  { label: '722 · Servicios de preparación de alimentos y bebidas', value: '722' },
  { label: '722511 · Restaurantes a la carta del sector privado', value: '722511' },
  { label: '722512 · Restaurantes de pescados y mariscos privado', value: '722512' },
  { label: '722513 · Restaurantes de comida rápida privado', value: '722513' },
  { label: '722514 · Taquerías y torterías', value: '722514' },
  { label: '722515 · Cafeterías, fuentes de sodas, neverías', value: '722515' },
  { label: '722517 · Cantinas, bares y similares', value: '722517' },
  
  // 81 - Otros servicios excepto actividades gubernamentales
  { label: '81 · Otros servicios excepto gubernamentales', value: '81' },
  { label: '811 · Servicios de reparación y mantenimiento', value: '811' },
  { label: '811111 · Talleres mecánicos automotrices', value: '811111' },
  { label: '811112 · Talleres de hojalatería y pintura', value: '811112' },
  { label: '811210 · Reparación de equipo electrónico y cómputo', value: '811210' },
  { label: '811310 · Reparación de maquinaria industrial', value: '811310' },
  { label: '812 · Servicios personales', value: '812' },
  { label: '812110 · Clínicas de belleza, estéticas y peluquerías', value: '812110' },
  { label: '812130 · Salones de masaje y baños públicos', value: '812130' },
  { label: '812310 · Lavanderías y tintorerías mecánicas', value: '812310' },
  { label: '812410 · Servicios de cerrajería', value: '812410' },
  { label: '813 · Asociaciones y organizaciones', value: '813' },
  
  // 93 - Actividades legislativas, gubernamentales, impartición de justicia y de organismos internacionales y extraterritoriales
  { label: '93 · Actividades gubernamentales', value: '93' }
];
